import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { AmbientBackground } from "@/components/background/AmbientBackground";
import { CustomCursor } from "@/components/motion/CustomCursor";
import { PaletteFavicon } from "@/components/brand/PaletteFavicon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Farrukh Noman - Full Stack Developer",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon/iris.png",
    shortcut: "/favicon/iris.png",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <PaletteFavicon />
          <AmbientBackground />
          <CustomCursor />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
